version: "3.7"
services:
  react:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  json-server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 3001:3001